title: "Md. Nazrul Islam"
description: "Md. Nazrul Islam, PhD Applicant; Lecturer Southeast University, Bangladesh; Research interest in Vision Language, Robotics, NLP, LLMs, Security of LLMs"
url: "https://nazrul-99.github.io"
baseurl: "/portfolio"

# Minimal Mistakes (remote theme)
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

defaults:
  - scope:
      path: ""
    values:
      data-theme: "dark"



plugins:
  - jekyll-include-cache
  - jemoji

author:
  name   : "Md. Nazrul Islam"
  avatar : "/assets/images/profile.jpg"
  bio    : "Vision Language, Robotics, NLP, LLMs, Security of LLMs."
  location: "Dhaka, Bangladesh"
  email: "nazrul.islam.cse.bd@gmail.com"
  links:
#    - label: "Email"
#      icon: "fas fa-envelope"
#      url: "mailto:nazrul.islam.cse.bd@gmail.com"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/nazrul-99"
    - label: "Google Scholar"
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/citations?user=qr34ziEAAAAJ&hl"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0002-6385-5095"
    - label: "ResearchGate"
      icon: "ai ai-researchgate"
      url: "https://www.researchgate.net/profile/Md-Nazrul-Islam-11"
    - label: "Website"
      icon: "fas fa-globe"
      url: "https://nazrul-99.github.io/portfolio/"
    - label: "CV (PDF)"
      icon: "fas fa-file-pdf"
      url: "/portfolio/assets/docs/cv.pdf"
#    - label: "Statement of Purpose"
#      icon: "fas fa-file-alt"
#      url: "/assets/docs/SoP_base.pdf"
#    - label: "Diversity Statement"
#      icon: "fas fa-users"
#      url: "/assets/docs/Diversity_Statement_base.pdf"

# Header (nav) comes from _data/navigation.yml
